"""Generate option, configuration and rule references from authoritative code."""
from __future__ import annotations

import argparse
import ast
from pathlib import Path

from tracemantle.cli import _build_parser
from tracemantle.config_loader import _KEY_MAP

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / 'docs/generated-reference.md'


def render() -> str:
    lines = ['# TraceMantle generated reference', '', 'Generated by `python scripts/generate_reference.py`; do not edit manually.', '', '## Validation CLI', '', '| Option | Default | Description |', '|---|---|---|']
    for action in _build_parser()._actions:
        if action.option_strings:
            help_text = str(action.help or '').replace('|', '\\|').replace('\n', ' ')
            lines.append(f"| `{', '.join(action.option_strings)}` | `{action.default}` | {help_text} |")
    lines.extend(['', '## Configuration keys', '', 'Under `[tool.tracemantle]` in pyproject.toml, or directly in tracemantle.toml.', '', '| Key | Setting |', '|---|---|'])
    for key, field in sorted(_KEY_MAP.items()):
        lines.append(f'| `{key}` | `{field}` |')
    lines.extend(['', '`frontmatter.extension_fields` and `frontmatter.reserved_words` are arrays of strings. The trusted `[tool.tracemantle.release]` policy is documented in [evidence-workflow.md](evidence-workflow.md).', '', '## Diagnostic rule IDs', ''])
    ids = set()
    for path in (ROOT / 'src/tracemantle').rglob('*.py'):
        for node in ast.walk(ast.parse(path.read_text())):
            if isinstance(node, ast.keyword) and node.arg == 'rule' and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
                ids.add(node.value.value)
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == 'Diagnostic' and node.args and isinstance(node.args[0], ast.Constant):
                ids.add(str(node.args[0].value))
    ids.update(f'frontmatter.{field}.type' for field in ('license', 'metadata', 'compatibility'))
    lines.extend(f'- `{rule}`' for rule in sorted(ids))
    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = render()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text() != output:
            raise SystemExit('Generated reference is stale; run python scripts/generate_reference.py.')
    else:
        DESTINATION.write_text(output)


if __name__ == '__main__':
    main()
